/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as ChangeLogRouteImport } from './routes/change-log'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SwapOrderIdRouteImport } from './routes/swap.$orderId'
import { Route as ApiPublicHooksSwapTickRouteImport } from './routes/api/public/hooks/swap-tick'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeLogRoute = ChangeLogRouteImport.update({
  id: '/change-log',
  path: '/change-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapOrderIdRoute = SwapOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => SwapRoute,
} as any)
const ApiPublicHooksSwapTickRoute = ApiPublicHooksSwapTickRouteImport.update({
  id: '/api/public/hooks/swap-tick',
  path: '/api/public/hooks/swap-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-log': typeof ChangeLogRoute
  '/swap': typeof SwapRouteWithChildren
  '/swap/$orderId': typeof SwapOrderIdRoute
  '/api/public/hooks/swap-tick': typeof ApiPublicHooksSwapTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-log': typeof ChangeLogRoute
  '/swap': typeof SwapRouteWithChildren
  '/swap/$orderId': typeof SwapOrderIdRoute
  '/api/public/hooks/swap-tick': typeof ApiPublicHooksSwapTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-log': typeof ChangeLogRoute
  '/swap': typeof SwapRouteWithChildren
  '/swap/$orderId': typeof SwapOrderIdRoute
  '/api/public/hooks/swap-tick': typeof ApiPublicHooksSwapTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-log'
    | '/swap'
    | '/swap/$orderId'
    | '/api/public/hooks/swap-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/change-log'
    | '/swap'
    | '/swap/$orderId'
    | '/api/public/hooks/swap-tick'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-log'
    | '/swap'
    | '/swap/$orderId'
    | '/api/public/hooks/swap-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangeLogRoute: typeof ChangeLogRoute
  SwapRoute: typeof SwapRouteWithChildren
  ApiPublicHooksSwapTickRoute: typeof ApiPublicHooksSwapTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-log': {
      id: '/change-log'
      path: '/change-log'
      fullPath: '/change-log'
      preLoaderRoute: typeof ChangeLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/$orderId': {
      id: '/swap/$orderId'
      path: '/$orderId'
      fullPath: '/swap/$orderId'
      preLoaderRoute: typeof SwapOrderIdRouteImport
      parentRoute: typeof SwapRoute
    }
    '/api/public/hooks/swap-tick': {
      id: '/api/public/hooks/swap-tick'
      path: '/api/public/hooks/swap-tick'
      fullPath: '/api/public/hooks/swap-tick'
      preLoaderRoute: typeof ApiPublicHooksSwapTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SwapRouteChildren {
  SwapOrderIdRoute: typeof SwapOrderIdRoute
}

const SwapRouteChildren: SwapRouteChildren = {
  SwapOrderIdRoute: SwapOrderIdRoute,
}

const SwapRouteWithChildren = SwapRoute._addFileChildren(SwapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangeLogRoute: ChangeLogRoute,
  SwapRoute: SwapRouteWithChildren,
  ApiPublicHooksSwapTickRoute: ApiPublicHooksSwapTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
