/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as EmbedBuilderRouteImport } from './routes/embed-builder'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as ChangeLogRouteImport } from './routes/change-log'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SwapIndexRouteImport } from './routes/swap.index'
import { Route as SwapOrderIdRouteImport } from './routes/swap.$orderId'
import { Route as ApiPublicHooksSwapTickRouteImport } from './routes/api/public/hooks/swap-tick'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedBuilderRoute = EmbedBuilderRouteImport.update({
  id: '/embed-builder',
  path: '/embed-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeLogRoute = ChangeLogRouteImport.update({
  id: '/change-log',
  path: '/change-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapIndexRoute = SwapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SwapRoute,
} as any)
const SwapOrderIdRoute = SwapOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => SwapRoute,
} as any)
const ApiPublicHooksSwapTickRoute = ApiPublicHooksSwapTickRouteImport.update({
  id: '/api/public/hooks/swap-tick',
  path: '/api/public/hooks/swap-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-log': typeof ChangeLogRoute
  '/embed': typeof EmbedRoute
  '/embed-builder': typeof EmbedBuilderRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRouteWithChildren
  '/terms': typeof TermsRoute
  '/swap/$orderId': typeof SwapOrderIdRoute
  '/swap/': typeof SwapIndexRoute
  '/api/public/hooks/swap-tick': typeof ApiPublicHooksSwapTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-log': typeof ChangeLogRoute
  '/embed': typeof EmbedRoute
  '/embed-builder': typeof EmbedBuilderRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/swap/$orderId': typeof SwapOrderIdRoute
  '/swap': typeof SwapIndexRoute
  '/api/public/hooks/swap-tick': typeof ApiPublicHooksSwapTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-log': typeof ChangeLogRoute
  '/embed': typeof EmbedRoute
  '/embed-builder': typeof EmbedBuilderRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRouteWithChildren
  '/terms': typeof TermsRoute
  '/swap/$orderId': typeof SwapOrderIdRoute
  '/swap/': typeof SwapIndexRoute
  '/api/public/hooks/swap-tick': typeof ApiPublicHooksSwapTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-log'
    | '/embed'
    | '/embed-builder'
    | '/exchange'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/swap'
    | '/terms'
    | '/swap/$orderId'
    | '/swap/'
    | '/api/public/hooks/swap-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/change-log'
    | '/embed'
    | '/embed-builder'
    | '/exchange'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/swap/$orderId'
    | '/swap'
    | '/api/public/hooks/swap-tick'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-log'
    | '/embed'
    | '/embed-builder'
    | '/exchange'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/swap'
    | '/terms'
    | '/swap/$orderId'
    | '/swap/'
    | '/api/public/hooks/swap-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangeLogRoute: typeof ChangeLogRoute
  EmbedRoute: typeof EmbedRoute
  EmbedBuilderRoute: typeof EmbedBuilderRoute
  ExchangeRoute: typeof ExchangeRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SwapRoute: typeof SwapRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiPublicHooksSwapTickRoute: typeof ApiPublicHooksSwapTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed-builder': {
      id: '/embed-builder'
      path: '/embed-builder'
      fullPath: '/embed-builder'
      preLoaderRoute: typeof EmbedBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-log': {
      id: '/change-log'
      path: '/change-log'
      fullPath: '/change-log'
      preLoaderRoute: typeof ChangeLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/': {
      id: '/swap/'
      path: '/'
      fullPath: '/swap/'
      preLoaderRoute: typeof SwapIndexRouteImport
      parentRoute: typeof SwapRoute
    }
    '/swap/$orderId': {
      id: '/swap/$orderId'
      path: '/$orderId'
      fullPath: '/swap/$orderId'
      preLoaderRoute: typeof SwapOrderIdRouteImport
      parentRoute: typeof SwapRoute
    }
    '/api/public/hooks/swap-tick': {
      id: '/api/public/hooks/swap-tick'
      path: '/api/public/hooks/swap-tick'
      fullPath: '/api/public/hooks/swap-tick'
      preLoaderRoute: typeof ApiPublicHooksSwapTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SwapRouteChildren {
  SwapOrderIdRoute: typeof SwapOrderIdRoute
  SwapIndexRoute: typeof SwapIndexRoute
}

const SwapRouteChildren: SwapRouteChildren = {
  SwapOrderIdRoute: SwapOrderIdRoute,
  SwapIndexRoute: SwapIndexRoute,
}

const SwapRouteWithChildren = SwapRoute._addFileChildren(SwapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangeLogRoute: ChangeLogRoute,
  EmbedRoute: EmbedRoute,
  EmbedBuilderRoute: EmbedBuilderRoute,
  ExchangeRoute: ExchangeRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SwapRoute: SwapRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiPublicHooksSwapTickRoute: ApiPublicHooksSwapTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
